name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - run: |
          sudo apt install -y python3-pip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev cmake libffi-dev libssl-dev
          pip install buildozer cython
          buildozer android debug
      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
